"""
Batch runner for penetration-rate experiments.

Execution rules
---------------
1. This script is designed for repeated experiments across multiple penetration
   values, for example:
      0.0, 0.1, 0.2, ..., 0.9

2. For a single penetration value, the execution order is always:
      main.py  ->  dashboard.py
   This order is mandatory because dashboard analysis depends on the files
   generated by main.py, such as:
      - fcd_<tag>.xml
      - stats_<tag>.xml
      - tls_<tag>.xml (urban signal scenarios)

3. Therefore, within one penetration task there is NO parallelism between
   simulation and dashboard export. They are executed sequentially.

4. Parallelism only happens across different penetration values. For example,
   p0.1, p0.2, and p0.3 may run in parallel as separate tasks, while each task
   still preserves:
      simulation first, dashboard second.

5. By default, this script:
      - runs main.py
      - then runs dashboard.py with --export-only
      - writes one log file per penetration

6. Optional modes:
      --skip_sim
          only run dashboard export for existing outputs
      --skip_dashboard
          only run simulation and skip dashboard export
      --rebuild_cache
          force dashboard.py to rebuild metrics cache

7. Important practical note:
   Since different penetration tasks write into the same scenario output
   folder structure, parallel execution assumes your workflow supports
   penetration-tagged output files safely. This project currently uses tagged
   files such as fcd_p0.2.xml and stats_p0.2.xml, which is why batch
   processing is feasible here.
"""

import argparse
import concurrent.futures
import os
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path


def format_penetration_tag(value: float) -> str:
    return f"p{value:g}"


def parse_penetrations(spec: str | None) -> list[float]:
    if spec is None or not spec.strip():
        return [round(i * 0.1, 10) for i in range(10)]

    items = []
    for token in spec.split(","):
        token = token.strip()
        if not token:
            continue
        items.append(round(float(token), 10))
    return items


@dataclass
class TaskResult:
    seed: int | None
    penetration: float
    ok: bool
    elapsed_s: float
    sim_returncode: int | None
    dashboard_returncode: int | None
    log_path: str
    error: str | None = None


def parse_seeds(spec: str | None, single_seed: int | None) -> list[int | None]:
    if spec is None or not spec.strip():
        return [single_seed]

    items: list[int] = []
    for token in spec.split(","):
        token = token.strip()
        if not token:
            continue
        items.append(int(token))
    if not items:
        return [single_seed]
    return items


def build_main_command(args, penetration: float, seed: int | None) -> list[str]:
    cmd = [
        sys.executable,
        "main.py",
        "--scenario_folder",
        args.scenario_folder,
        "--scenario",
        args.scenario,
        "--backend",
        args.backend,
        "--penetration",
        f"{penetration:g}",
    ]

    if seed is not None:
        cmd.extend(["--seed", str(seed)])
    if args.realtime:
        cmd.append("--realtime")
    if args.no_cav_onramp:
        cmd.append("--no_cav_onramp")
    if args.no_cav_lanechange:
        cmd.append("--no_cav_lanechange")
    if args.no_inflow:
        cmd.append("--no_inflow")
    if args.timestamp_output:
        cmd.append("--timestamp_output")
    if args.log_tl:
        cmd.append("--log_tl")
    if args.debug:
        cmd.append("--debug")
    if args.gui:
        cmd.append("--gui")
    if getattr(args, 'max_sim_time', 0):
        cmd.extend(["--max_sim_time", str(args.max_sim_time)])
    return cmd


def build_dashboard_command(args, penetration: float, seed: int | None) -> list[str]:
    cmd = [
        sys.executable,
        "dashboard.py",
        "--scenario_folder",
        args.scenario_folder,
        "--scenario",
        args.scenario,
        "--p",
        f"{penetration:g}",
        "--urban",
        args.urban,
        "--export-only",
    ]
    if seed is not None:
        cmd.extend(["--seed", str(seed)])
    if args.rebuild_cache:
        cmd.append("--rebuild-cache")
    return cmd


def run_subprocess(cmd: list[str], log_file) -> int:
    log_file.write(f"$ {' '.join(cmd)}\n")
    log_file.flush()
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    env["PYTHONUTF8"] = "1"
    proc = subprocess.Popen(
        cmd,
        stdout=log_file,
        stderr=subprocess.STDOUT,
        cwd=os.getcwd(),
        text=True,
        env=env,
    )
    return proc.wait()


def run_one_penetration(args, penetration: float, logs_dir: str, seed: int | None) -> TaskResult:
    """
    Run one complete penetration experiment.

    Order of operations:
    1. Run main.py for the given penetration.
    2. If simulation succeeds, run dashboard.py in export-only mode.
    3. Save all stdout/stderr to one penetration-specific log file.

    This function is sequential by design because dashboard export depends on
    the simulation outputs from the same penetration value.
    """
    tag = format_penetration_tag(penetration)
    seed_suffix = f"_seed{seed}" if seed is not None else ""
    log_path = os.path.join(logs_dir, f"{args.scenario}_{tag}{seed_suffix}.log")
    t0 = time.perf_counter()
    sim_rc = None
    dash_rc = None

    try:
        with open(log_path, "w", encoding="utf-8") as log_file:
            log_file.write(f"=== Batch run for penetration {penetration:g} ({tag}) ===\n")
            log_file.write(f"Seed: {seed if seed is not None else 'default'}\n")
            log_file.write(f"Started at {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            log_file.flush()

            if not args.skip_sim:
                sim_cmd = build_main_command(args, penetration, seed)
                sim_rc = run_subprocess(sim_cmd, log_file)
                if sim_rc != 0:
                    return TaskResult(
                        seed=seed,
                        penetration=penetration,
                        ok=False,
                        elapsed_s=time.perf_counter() - t0,
                        sim_returncode=sim_rc,
                        dashboard_returncode=None,
                        log_path=log_path,
                        error="main.py failed",
                    )

            if not args.skip_dashboard:
                dash_cmd = build_dashboard_command(args, penetration, seed)
                dash_rc = run_subprocess(dash_cmd, log_file)
                if dash_rc != 0:
                    return TaskResult(
                        seed=seed,
                        penetration=penetration,
                        ok=False,
                        elapsed_s=time.perf_counter() - t0,
                        sim_returncode=sim_rc,
                        dashboard_returncode=dash_rc,
                        log_path=log_path,
                        error="dashboard.py failed",
                    )

        return TaskResult(
            seed=seed,
            penetration=penetration,
            ok=True,
            elapsed_s=time.perf_counter() - t0,
            sim_returncode=sim_rc,
            dashboard_returncode=dash_rc,
            log_path=log_path,
        )
    except Exception as e:
        return TaskResult(
            seed=seed,
            penetration=penetration,
            ok=False,
            elapsed_s=time.perf_counter() - t0,
            sim_returncode=sim_rc,
            dashboard_returncode=dash_rc,
            log_path=log_path,
            error=str(e),
        )


def main():
    parser = argparse.ArgumentParser(description="Batch-run SUMO simulation and dashboard exports across multiple penetration rates.")
    parser.add_argument("--scenario_folder", default="sumo_scenarios", type=str)
    parser.add_argument("--scenario", default="roosevelt", type=str)
    parser.add_argument("--backend", default="traci", type=str)
    parser.add_argument("--urban", choices=["auto", "yes", "no"], default="auto")
    parser.add_argument(
        "--penetrations",
        default=None,
        type=str,
        help="Comma-separated penetration list, e.g. 0,0.1,0.2,0.3 . Default: 0.0 to 0.9 in 0.1 steps.",
    )
    parser.add_argument("--workers", default=max(1, min(4, (os.cpu_count() or 2) // 2)), type=int)
    parser.add_argument("--seed", default=None, type=int)
    parser.add_argument("--seeds", default=None, type=str, help="Comma-separated seeds, e.g. 23423,23424 . Runs seeds sequentially and penetrations in parallel within each seed.")
    parser.add_argument("--logs_dir", default=None, type=str)
    parser.add_argument("--skip_sim", action="store_true", help="Skip main.py and only run dashboard exports.")
    parser.add_argument("--skip_dashboard", action="store_true", help="Skip dashboard.py exports and only run main.py.")
    parser.add_argument("--rebuild_cache", action="store_true", help="Force dashboard.py to rebuild cached metrics.")
    parser.add_argument("--gui", action="store_true", help="Launch SUMO GUI for each simulation. Not recommended for parallel batch runs.")
    parser.add_argument("--realtime", action="store_true")
    parser.add_argument("--no_cav_onramp", action="store_true")
    parser.add_argument("--no_cav_lanechange", action="store_true")
    parser.add_argument("--no_inflow", action="store_true")
    parser.add_argument("--timestamp_output", action="store_true")
    parser.add_argument("--log_tl", action="store_true")
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--max_sim_time", default=0, type=float,
        help="Hard cap on simulation time in seconds. 0 = disabled. Recommended: 3600 for roosevelt.")

    args = parser.parse_args()

    penetrations = parse_penetrations(args.penetrations)
    seeds = parse_seeds(args.seeds, args.seed)
    if not penetrations:
        raise SystemExit("No valid penetration values were provided.")

    scenario_root = Path(args.scenario_folder) / args.scenario
    logs_dir = Path(args.logs_dir) if args.logs_dir else scenario_root / "batch_logs"
    logs_dir.mkdir(parents=True, exist_ok=True)

    print(f"Batch run scenario: {args.scenario}")
    print(f"Penetrations: {', '.join(f'{p:g}' for p in penetrations)}")
    print(f"Seeds: {', '.join('default' if s is None else str(s) for s in seeds)}")
    print(f"Workers: {args.workers}")
    print(f"Logs directory: {logs_dir}")

    t0 = time.perf_counter()
    results: list[TaskResult] = []

    for seed in seeds:
        seed_label = "default" if seed is None else str(seed)
        print(f"\nRunning seed: {seed_label}")
        with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as executor:
            future_map = {
                executor.submit(run_one_penetration, args, pen, str(logs_dir), seed): pen
                for pen in penetrations
            }
            for future in concurrent.futures.as_completed(future_map):
                result = future.result()
                results.append(result)
                tag = format_penetration_tag(result.penetration)
                status = "OK" if result.ok else "FAILED"
                print(f"[{status}] {tag} seed={seed_label} in {result.elapsed_s:.1f}s -> {result.log_path}")
                if result.error:
                    print(f"        reason: {result.error}")

    total_elapsed = time.perf_counter() - t0
    results.sort(key=lambda r: ((-1 if r.seed is None else r.seed), r.penetration))
    ok_count = sum(1 for r in results if r.ok)
    fail_count = len(results) - ok_count

    print("\nBatch summary")
    print(f"  Total tasks : {len(results)}")
    print(f"  Succeeded   : {ok_count}")
    print(f"  Failed      : {fail_count}")
    print(f"  Wall time   : {total_elapsed:.1f}s")

    if fail_count:
        print("\nFailed runs")
        for result in results:
            if not result.ok:
                seed_label = "default" if result.seed is None else str(result.seed)
                print(f"  seed={seed_label} | p={result.penetration:g} | log={result.log_path} | error={result.error}")
        raise SystemExit(1)


if __name__ == "__main__":
    main()
